### PR TITLE
Readme content

### PR DESCRIPTION
**Pull request by SteveLasker**
Signed-off-by: Steve Lasker <stevenlasker@hotmail.com>

### CODE REVIEW

**Review by sajayantony — CHANGES_REQUESTED** [review]
Has the governance already made it into the repo?

**Comment by SteveLasker** [comment]
> Has the governance already made it into the repo?
Not yet. Just trying to avoid a bunch of conflicting and chained PRs. Hoping these both get merged today and they just "blend" together"

**Comment by sajayantony** [comment]
This PR is incomplete or pointing to non-existent media. So let's queue this up once governance is merged since that being the first PR sets good precedence for future work - https://github.com/oras-project/community/pull/1

**Review by sajayantony — APPROVED** [review]
Please merge after  #1 is merged.

**Review by sajayantony — APPROVED** [review]

**Pull request merged**
