### PR TITLE
chore: Add subproject owners to a central place

### PR DESCRIPTION
**Pull request by FeynmanZhou**
Fix https://github.com/oras-project/community/issues/23 also one item of https://github.com/oras-project/community/issues/28].

If this PR is approved and merged, we will sync it to the [CNCF maintainer list](https://github.com/cncf/foundation/blob/main/project-maintainers.csv).

### CODE REVIEW

**Review by sajayantony — APPROVED** [review]

**Review by SteveLasker — APPROVED** [review]
Approving to get CNCF unblocked.
That said, as noted in some of the other ORAS and Notary PRs, the relationship between `CODEOWNERS`, `MAINTAINERS`, GitHub Teams, Org and now this `SUBPROJECT_OWNERS` file is quite confusing. 
I believe CNCF is looking for a consolidated list to point to, as noted above. This does serve the purpose, so LGTM. I just wonder how these files will stay maintained, over time.

**Review by shizhMSFT — APPROVED** [review]
LGTM

**Comment by FeynmanZhou** [comment]
> Approving to get CNCF unblocked. That said, as noted in some of the other ORAS and Notary PRs, the relationship between `CODEOWNERS`, `MAINTAINERS`, GitHub Teams, Org and now this `SUBPROJECT_OWNERS` file is quite confusing. I believe CNCF is looking for a consolidated list to point to, as noted above. This does serve the purpose, so LGTM. I just wonder how these files will stay maintained, over time.

@SteveLasker Thanks for the heads up. You are correct. CNCF just needs a consolidated maintainer list as a reference. 
MAINTAINERS is a new role we are defining, it has the [maintain permission](https://docs.github.com/en/organizations/managing-user-access-to-your-organizations-repositories/repository-roles-for-an-organization#permissions-for-each-role) in the repo. The existing `OWNERS` are the repo admin.

**Review by sajayantony — CHANGES_REQUESTED** [review]
I think we should discuss this a bit more. Having 3 owner related files makes it really hard to understanding. Maybe add comments to each or collapse them and create an ORG repo for CNCF related operations.

**Comment by SteveLasker** [comment]
> I think we should discuss this a bit more. Having 3 owner related files makes it really hard to understanding. Maybe add comments to each or collapse them and create an ORG repo for CNCF related operations.

Can we place the relationship of the multiple files in the governance docs?
Then, the files could have a comment, pointing to the governance docs as reference.
I'm also trying to re-use these in other projects that are also trying to solve the same problem of org and sub-project ownership. 
I think this is another place to represent a great source of copy/paste for bootstrapping a new project.

**Comment by SteveLasker** [comment]
Based on our weekly meeting, I've added #36 to supersede this PR.

**Comment by SteveLasker** [comment]
@FeynmanZhou, can we close this, and review/merge #36?

**Pull request closed without merging**
