### PR TITLE
add ROADMAP.md

### PR DESCRIPTION
**Pull request by FeynmanZhou**
Adding ROADMAP.md with the planned milestones and timeline.

### CODE REVIEW

**Comment by FeynmanZhou** [comment]
@oras-project/oras-maintainers Could you please help to review this PR?

**Review by SteveLasker — APPROVED** [review]
The changes look good.
Based on other projects, it's been hard to maintain a roadmap as a static document. I wonder if we should use the github project boards to show live planning/roadmap updates. This way it's always reflecting the plan, and not having to do PRs to a markdown page.

**Comment by FeynmanZhou** [comment]
> The changes look good. Based on other projects, it's been hard to maintain a roadmap as a static document. I wonder if we should use the github project boards to show live planning/roadmap updates. This way it's always reflecting the plan, and not having to do PRs to a markdown page.



> The changes look good. Based on other projects, it's been hard to maintain a roadmap as a static document. I wonder if we should use the github project boards to show live planning/roadmap updates. This way it's always reflecting the plan, and not having to do PRs to a markdown page.

@SteveLasker 
Good catch. I list the [ORAS planning board](https://github.com/orgs/oras-project/projects/2/views/2) at the beginning of this Roadmap for fine-grained tracking of all issues. 

This roadmap is giving a high-level plan so that people can easily understand the core features planned in the next few milestones and when will they can be released. It reflects a regular delivery rhythm of an OSS project in the community.

**Comment by SteveLasker** [comment]
> @SteveLasker Good catch. I listed the [ORAS planning board](https://github.com/orgs/oras-project/projects/2/views/2) at the beginning of this Roadmap for fine-grained tracking of all issues.

Sounds good. I'd be fine merging this list as a first start. I'm just worried about it getting stale, so we can pick it up for the next post.

**Review by sajayantony — APPROVED** [review]

**Comment by FeynmanZhou** [comment]
@sajayantony Can you merge this PR if it looks good to you? The Roadmap was linked in the [ORAS blog post](https://github.com/oras-project/oras-www/pull/55/files#diff-af43525124ec8a0512a648e97646e1e106d92ca7117551a4ca6020d147cd503bL110), I want to avoid the broken link in that blog.

**Pull request merged**
