### PR TITLE
Updated README.md

### PR DESCRIPTION
**Pull request by pranjit-medhi**

### CODE REVIEW

**Review by pranjit-medhi — COMMENTED** [review]
updated the roadmap.md link on readme file

**Comment by SteveLasker** [comment]
Dupe of #27 - which I just noticed this was first.
But, note the comment in #27. Either could be merged, or one could fix the casing on the text of the link.

**Comment by sajayantony** [comment]
Should have taken this if this was the earlier PR compared to #27. Sorry @pranjit-medhi

**Comment by sajayantony** [comment]
On a side note , for following PRs you can make pass using `git commit -s`

**Comment by TerryHowe** [comment]
Done in other #27

**Pull request closed without merging**
